name: wavelog_client
description: Pure-Dart client for the Wavelog API v2.
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.13.0

dev_dependencies:
  test: any
  very_good_analysis: ^11.0.0
  wavelog_mock: any
dependencies:
  http: ^1.6.0
  meta: ^1.19.0
