// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    accounts,
    stationProfiles,
    contestDefinitions,
    contestSessions,
    activations,
    qsos,
    qsoSync,
    syncJournal,
    contestLinks,
    serialAllocations,
    programRules,
    referencePacks,
    dxccEntities,
    dxccPrefixes,
    programReferences,
    scpCalls,
    workedBefore,
    devices,
    peerCursors,
    settings,
    shortcutBindings,
    qsosAccountTime,
    qsosCall,
    qsosContestSession,
    qsoSyncAccountState,
    syncJournalAccountAt,
  ];
  late final Shape0 accounts = Shape0(
    source: i0.VersionedTable(
      entityName: 'accounts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 stationProfiles = Shape1(
    source: i0.VersionedTable(
      entityName: 'station_profiles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(account_id, remote_id)'],
      columns: [
        _column_0,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 contestDefinitions = Shape2(
    source: i0.VersionedTable(
      entityName: 'contest_definitions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_12,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 contestSessions = Shape3(
    source: i0.VersionedTable(
      entityName: 'contest_sessions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_0,
        _column_36,
        _column_10,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 activations = Shape4(
    source: i0.VersionedTable(
      entityName: 'activations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_0,
        _column_10,
        _column_48,
        _column_49,
        _column_50,
        _column_37,
        _column_38,
        _column_39,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 qsos = Shape5(
    source: i0.VersionedTable(
      entityName: 'qsos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_0,
        _column_10,
        _column_37,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_64,
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_21,
        _column_18,
        _column_19,
        _column_20,
        _column_22,
        _column_23,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_73,
        _column_74,
        _column_75,
        _column_50,
        _column_76,
        _column_77,
        _column_78,
        _column_79,
        _column_80,
        _column_81,
        _column_82,
        _column_83,
        _column_84,
        _column_85,
        _column_86,
        _column_87,
        _column_88,
        _column_89,
        _column_90,
        _column_91,
        _column_92,
        _column_93,
        _column_94,
        _column_95,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 qsoSync = Shape6(
    source: i0.VersionedTable(
      entityName: 'qso_sync',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(qso_id, account_id)'],
      columns: [
        _column_96,
        _column_10,
        _column_97,
        _column_98,
        _column_99,
        _column_100,
        _column_101,
        _column_102,
        _column_103,
        _column_104,
        _column_105,
        _column_106,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 syncJournal = Shape7(
    source: i0.VersionedTable(
      entityName: 'sync_journal',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_107,
        _column_10,
        _column_108,
        _column_109,
        _column_110,
        _column_111,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 contestLinks = Shape8(
    source: i0.VersionedTable(
      entityName: 'contest_links',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(session_id, qso_id)'],
      columns: [_column_112, _column_96, _column_113, _column_114],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 serialAllocations = Shape9(
    source: i0.VersionedTable(
      entityName: 'serial_allocations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(session_id, serial)'],
      columns: [_column_112, _column_115, _column_108, _column_116],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 programRules = Shape10(
    source: i0.VersionedTable(
      entityName: 'program_rules',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(program)'],
      columns: [_column_48, _column_28, _column_117],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 referencePacks = Shape11(
    source: i0.VersionedTable(
      entityName: 'reference_packs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_118,
        _column_119,
        _column_120,
        _column_121,
        _column_25,
        _column_122,
        _column_123,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 dxccEntities = Shape12(
    source: i0.VersionedTable(
      entityName: 'dxcc_entities',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(dxcc)'],
      columns: [
        _column_124,
        _column_12,
        _column_125,
        _column_126,
        _column_127,
        _column_128,
        _column_129,
        _column_130,
        _column_131,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 dxccPrefixes = Shape13(
    source: i0.VersionedTable(
      entityName: 'dxcc_prefixes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(prefix_or_call, exact)'],
      columns: [
        _column_132,
        _column_133,
        _column_134,
        _column_135,
        _column_136,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 programReferences = Shape14(
    source: i0.VersionedTable(
      entityName: 'program_references',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(program, ref)'],
      columns: [
        _column_48,
        _column_137,
        _column_12,
        _column_138,
        _column_139,
        _column_140,
        _column_141,
        _column_142,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 scpCalls = Shape15(
    source: i0.VersionedTable(
      entityName: 'scp_calls',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(call)'],
      columns: [_column_51],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape16 workedBefore = Shape16(
    source: i0.VersionedTable(
      entityName: 'worked_before',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(account_id, call, band, mode)'],
      columns: [
        _column_10,
        _column_51,
        _column_54,
        _column_56,
        _column_15,
        _column_14,
        _column_143,
        _column_144,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 devices = Shape17(
    source: i0.VersionedTable(
      entityName: 'devices',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_12, _column_145, _column_146, _column_147],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape18 peerCursors = Shape18(
    source: i0.VersionedTable(
      entityName: 'peer_cursors',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(device_id)'],
      columns: [_column_148, _column_149],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape19 settings = Shape19(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_150, _column_151],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape20 shortcutBindings = Shape20(
    source: i0.VersionedTable(
      entityName: 'shortcut_bindings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(command_id, platform)'],
      columns: [_column_152, _column_153, _column_154],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index qsosAccountTime = i1.Index(
    'qsos_account_time',
    'CREATE INDEX qsos_account_time ON qsos (account_id, time_on)',
  );
  final i1.Index qsosCall = i1.Index(
    'qsos_call',
    'CREATE INDEX qsos_call ON qsos (call)',
  );
  final i1.Index qsosContestSession = i1.Index(
    'qsos_contest_session',
    'CREATE INDEX qsos_contest_session ON qsos (contest_session_id)',
  );
  final i1.Index qsoSyncAccountState = i1.Index(
    'qso_sync_account_state',
    'CREATE INDEX qso_sync_account_state ON qso_sync (account_id, state)',
  );
  final i1.Index syncJournalAccountAt = i1.Index(
    'sync_journal_account_at',
    'CREATE INDEX sync_journal_account_at ON sync_journal (account_id, at)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get label =>
      columnsByName['label']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get baseUrl =>
      columnsByName['base_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get usesIndexPhp =>
      columnsByName['uses_index_php']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get certPinSha256 =>
      columnsByName['cert_pin_sha256']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get allowHttpLan =>
      columnsByName['allow_http_lan']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get serverCaps =>
      columnsByName['server_caps']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get scopes =>
      columnsByName['scopes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get tokenExpiresAt =>
      columnsByName['token_expires_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'label',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'base_url',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'uses_index_php',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (uses_index_php IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<String> _column_4(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cert_pin_sha256',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'allow_http_lan',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (allow_http_lan IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'server_caps',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'{}\'',
      defaultValue: const i1.CustomExpression('\'{}\''),
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'scopes',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );
i1.GeneratedColumn<int> _column_8(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'token_expires_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get accountId =>
      columnsByName['account_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get remoteId =>
      columnsByName['remote_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get callsign =>
      columnsByName['callsign']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get gridsquare =>
      columnsByName['gridsquare']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get dxcc =>
      columnsByName['dxcc']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cqz =>
      columnsByName['cqz']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get ituz =>
      columnsByName['ituz']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get sotaRef =>
      columnsByName['sota_ref']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get potaRef =>
      columnsByName['pota_ref']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get wwffRef =>
      columnsByName['wwff_ref']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get iota =>
      columnsByName['iota']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sig =>
      columnsByName['sig']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sigInfo =>
      columnsByName['sig_info']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get active =>
      columnsByName['active']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get fetchedAt =>
      columnsByName['fetched_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'account_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES accounts(id)',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'remote_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'callsign',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'gridsquare',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'dxcc',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cqz',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ituz',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sota_ref',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'pota_ref',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_20(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'wwff_ref',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'iota',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sig',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sig_info',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'active',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (active IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'fetched_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cabrilloName =>
      columnsByName['cabrillo_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get wavelogAdifName =>
      columnsByName['wavelog_adif_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get definition =>
      columnsByName['definition']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get builtin =>
      columnsByName['builtin']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_26(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cabrillo_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'wavelog_adif_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'definition',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'builtin',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (builtin IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get originDeviceId =>
      columnsByName['origin_device_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get hlcCreated =>
      columnsByName['hlc_created']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get hlcModified =>
      columnsByName['hlc_modified']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get rev =>
      columnsByName['rev']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get definitionId =>
      columnsByName['definition_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get accountId =>
      columnsByName['account_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get stationProfileId =>
      columnsByName['station_profile_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startedAt =>
      columnsByName['started_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endedAt =>
      columnsByName['ended_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get settings =>
      columnsByName['settings']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get remoteSessionId =>
      columnsByName['remote_session_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get serialStrategy =>
      columnsByName['serial_strategy']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get serialRangeStart =>
      columnsByName['serial_range_start']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get serialRangeEnd =>
      columnsByName['serial_range_end']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get remoteState =>
      columnsByName['remote_state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get remoteEndSynced =>
      columnsByName['remote_end_synced']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get remoteErrorKey =>
      columnsByName['remote_error_key']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'origin_device_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_32(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'hlc_created',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'hlc_modified',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_34(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'rev',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1',
      defaultValue: const i1.CustomExpression('1'),
    );
i1.GeneratedColumn<int> _column_35(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'deleted_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'definition_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES contest_definitions(id)',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'station_profile_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES station_profiles(id)',
    );
i1.GeneratedColumn<int> _column_38(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'started_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ended_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'settings',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'{}\'',
      defaultValue: const i1.CustomExpression('\'{}\''),
    );
i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'remote_session_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'serial_strategy',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'single\'',
      defaultValue: const i1.CustomExpression('\'single\''),
    );
i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'serial_range_start',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_44(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'serial_range_end',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_45(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'remote_state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'local\'',
      defaultValue: const i1.CustomExpression('\'local\''),
    );
i1.GeneratedColumn<int> _column_46(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'remote_end_synced',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'remote_error_key',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get originDeviceId =>
      columnsByName['origin_device_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get hlcCreated =>
      columnsByName['hlc_created']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get hlcModified =>
      columnsByName['hlc_modified']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get rev =>
      columnsByName['rev']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get accountId =>
      columnsByName['account_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get program =>
      columnsByName['program']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get reference =>
      columnsByName['reference']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get myGridsquare =>
      columnsByName['my_gridsquare']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get stationProfileId =>
      columnsByName['station_profile_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get startedAt =>
      columnsByName['started_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endedAt =>
      columnsByName['ended_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_48(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'program',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_49(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'reference',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'my_gridsquare',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get originDeviceId =>
      columnsByName['origin_device_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get hlcCreated =>
      columnsByName['hlc_created']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get hlcModified =>
      columnsByName['hlc_modified']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get rev =>
      columnsByName['rev']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get accountId =>
      columnsByName['account_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get stationProfileId =>
      columnsByName['station_profile_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get call =>
      columnsByName['call']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get timeOn =>
      columnsByName['time_on']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get timeOff =>
      columnsByName['time_off']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get band =>
      columnsByName['band']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bandRx =>
      columnsByName['band_rx']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mode =>
      columnsByName['mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get submode =>
      columnsByName['submode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get freqHz =>
      columnsByName['freq_hz']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get freqRxHz =>
      columnsByName['freq_rx_hz']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get rstSent =>
      columnsByName['rst_sent']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get rstRcvd =>
      columnsByName['rst_rcvd']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get qth =>
      columnsByName['qth']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get gridsquare =>
      columnsByName['gridsquare']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get dxcc =>
      columnsByName['dxcc']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cqz =>
      columnsByName['cqz']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get ituz =>
      columnsByName['ituz']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get state =>
      columnsByName['state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cnty =>
      columnsByName['cnty']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get country =>
      columnsByName['country']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get cont =>
      columnsByName['cont']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get darcDok =>
      columnsByName['darc_dok']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get iota =>
      columnsByName['iota']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sotaRef =>
      columnsByName['sota_ref']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get potaRef =>
      columnsByName['pota_ref']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get wwffRef =>
      columnsByName['wwff_ref']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sig =>
      columnsByName['sig']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sigInfo =>
      columnsByName['sig_info']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mySotaRef =>
      columnsByName['my_sota_ref']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get myPotaRef =>
      columnsByName['my_pota_ref']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get myWwffRef =>
      columnsByName['my_wwff_ref']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mySig =>
      columnsByName['my_sig']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mySigInfo =>
      columnsByName['my_sig_info']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get stationCallsign =>
      columnsByName['station_callsign']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get operator =>
      columnsByName['operator']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get myGridsquare =>
      columnsByName['my_gridsquare']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get txPwr =>
      columnsByName['tx_pwr']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<String> get contestId =>
      columnsByName['contest_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get srx =>
      columnsByName['srx']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get stx =>
      columnsByName['stx']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get srxString =>
      columnsByName['srx_string']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get stxString =>
      columnsByName['stx_string']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get check =>
      columnsByName['check']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get class$ =>
      columnsByName['class']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get precedence =>
      columnsByName['precedence']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get arrlSect =>
      columnsByName['arrl_sect']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get propMode =>
      columnsByName['prop_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get satName =>
      columnsByName['sat_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get satMode =>
      columnsByName['sat_mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get comment =>
      columnsByName['comment']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get notes =>
      columnsByName['notes']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get qslVia =>
      columnsByName['qsl_via']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get adifExtra =>
      columnsByName['adif_extra']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contestSessionId =>
      columnsByName['contest_session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get activationId =>
      columnsByName['activation_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'call',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_52(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'time_on',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_53(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'time_off',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'band',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'band_rx',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_56(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'mode',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_57(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'submode',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_58(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'freq_hz',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_59(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'freq_rx_hz',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_60(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'rst_sent',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_61(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'rst_rcvd',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_62(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_63(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'qth',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_64(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'state',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_65(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cnty',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_66(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'country',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_67(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cont',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_68(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'darc_dok',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_69(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'my_sota_ref',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_70(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'my_pota_ref',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_71(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'my_wwff_ref',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_72(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'my_sig',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_73(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'my_sig_info',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_74(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'station_callsign',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_75(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'operator',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_76(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'tx_pwr',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_77(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'contest_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_78(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'srx',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_79(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'stx',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_80(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'srx_string',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_81(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'stx_string',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_82(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'check',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_83(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'class',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_84(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'precedence',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_85(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'arrl_sect',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_86(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'prop_mode',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_87(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sat_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_88(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sat_mode',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_89(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'comment',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_90(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'notes',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_91(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'qsl_via',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_92(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'adif_extra',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'{}\'',
      defaultValue: const i1.CustomExpression('\'{}\''),
    );
i1.GeneratedColumn<String> _column_93(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'contest_session_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES contest_sessions(id)',
    );
i1.GeneratedColumn<String> _column_94(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'activation_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES activations(id)',
    );
i1.GeneratedColumn<String> _column_95(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'manual\'',
      defaultValue: const i1.CustomExpression('\'manual\''),
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get qsoId =>
      columnsByName['qso_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get accountId =>
      columnsByName['account_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get state =>
      columnsByName['state']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get operation =>
      columnsByName['operation']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get remoteQsoId =>
      columnsByName['remote_qso_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get attempts =>
      columnsByName['attempts']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get nextAttemptAt =>
      columnsByName['next_attempt_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastErrorCode =>
      columnsByName['last_error_code']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastErrorKey =>
      columnsByName['last_error_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get serverMessage =>
      columnsByName['server_message']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get syncedRev =>
      columnsByName['synced_rev']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get syncedHash =>
      columnsByName['synced_hash']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_96(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'qso_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES qsos(id)',
    );
i1.GeneratedColumn<String> _column_97(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'state',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_98(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'operation',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'create\'',
      defaultValue: const i1.CustomExpression('\'create\''),
    );
i1.GeneratedColumn<int> _column_99(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'remote_qso_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_100(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'attempts',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_101(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'next_attempt_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_102(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_error_code',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_103(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_error_key',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_104(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'server_message',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_105(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'synced_rev',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_106(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'synced_hash',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get accountId =>
      columnsByName['account_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get qsoId =>
      columnsByName['qso_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get at =>
      columnsByName['at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get event =>
      columnsByName['event']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get detail =>
      columnsByName['detail']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_107(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_108(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'qso_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_109(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_110(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'event',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_111(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'detail',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'{}\'',
      defaultValue: const i1.CustomExpression('\'{}\''),
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get qsoId =>
      columnsByName['qso_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get remoteQsoId =>
      columnsByName['remote_qso_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get linkedAt =>
      columnsByName['linked_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_112(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'session_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES contest_sessions(id)',
    );
i1.GeneratedColumn<int> _column_113(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'remote_qso_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_114(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'linked_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get sessionId =>
      columnsByName['session_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get serial =>
      columnsByName['serial']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get qsoId =>
      columnsByName['qso_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get allocatedAt =>
      columnsByName['allocated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_115(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'serial',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_116(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'allocated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get program =>
      columnsByName['program']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get rules =>
      columnsByName['rules']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_117(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'rules',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get version =>
      columnsByName['version']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sourceUrl =>
      columnsByName['source_url']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get sha256 =>
      columnsByName['sha256']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get fetchedAt =>
      columnsByName['fetched_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get regionFilter =>
      columnsByName['region_filter']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get licenceNote =>
      columnsByName['licence_note']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_118(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_119(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'version',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_120(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source_url',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_121(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'sha256',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_122(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'region_filter',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_123(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'licence_note',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get dxcc =>
      columnsByName['dxcc']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get prefix =>
      columnsByName['prefix']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get cqz =>
      columnsByName['cqz']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get ituz =>
      columnsByName['ituz']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get cont =>
      columnsByName['cont']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get lat =>
      columnsByName['lat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get lon =>
      columnsByName['lon']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get deleted =>
      columnsByName['deleted']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_124(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'dxcc',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_125(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'prefix',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_126(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cqz',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_127(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ituz',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_128(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'cont',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_129(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'lat',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<double> _column_130(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'lon',
      aliasedName,
      false,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_131(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'deleted',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (deleted IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get prefixOrCall =>
      columnsByName['prefix_or_call']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get exact =>
      columnsByName['exact']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get dxcc =>
      columnsByName['dxcc']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cqzOverride =>
      columnsByName['cqz_override']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get ituzOverride =>
      columnsByName['ituz_override']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_132(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'prefix_or_call',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_133(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'exact',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (exact IN (0, 1))',
    );
i1.GeneratedColumn<int> _column_134(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'dxcc',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES dxcc_entities(dxcc)',
    );
i1.GeneratedColumn<int> _column_135(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cqz_override',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_136(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ituz_override',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get program =>
      columnsByName['program']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ref =>
      columnsByName['ref']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get region =>
      columnsByName['region']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get lat =>
      columnsByName['lat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get lon =>
      columnsByName['lon']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get validFrom =>
      columnsByName['valid_from']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get validTo =>
      columnsByName['valid_to']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_137(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'ref',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_138(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'region',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_139(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'lat',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<double> _column_140(String aliasedName) =>
    i1.GeneratedColumn<double>(
      'lon',
      aliasedName,
      true,
      type: i1.DriftSqlType.double,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_141(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'valid_from',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_142(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'valid_to',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape15 extends i0.VersionedTable {
  Shape15({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get call =>
      columnsByName['call']! as i1.GeneratedColumn<String>;
}

class Shape16 extends i0.VersionedTable {
  Shape16({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get accountId =>
      columnsByName['account_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get call =>
      columnsByName['call']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get band =>
      columnsByName['band']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get mode =>
      columnsByName['mode']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get dxcc =>
      columnsByName['dxcc']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get gridsquare =>
      columnsByName['gridsquare']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get firstTime =>
      columnsByName['first_time']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get source =>
      columnsByName['source']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_143(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'first_time',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_144(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'source',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape17 extends i0.VersionedTable {
  Shape17({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get publicKey =>
      columnsByName['public_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get pairedAt =>
      columnsByName['paired_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get revokedAt =>
      columnsByName['revoked_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_145(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'public_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_146(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'paired_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_147(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'revoked_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape18 extends i0.VersionedTable {
  Shape18({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get deviceId =>
      columnsByName['device_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get lastHlc =>
      columnsByName['last_hlc']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_148(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'device_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES devices(id)',
    );
i1.GeneratedColumn<String> _column_149(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_hlc',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape19 extends i0.VersionedTable {
  Shape19({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_150(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_151(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape20 extends i0.VersionedTable {
  Shape20({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get commandId =>
      columnsByName['command_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get platform =>
      columnsByName['platform']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get binding =>
      columnsByName['binding']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_152(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'command_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_153(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'platform',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_154(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'binding',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    accounts,
    stationProfiles,
    contestDefinitions,
    contestSessions,
    activations,
    qsos,
    qsoSync,
    syncJournal,
    contestLinks,
    serialAllocations,
    programRules,
    referencePacks,
    dxccEntities,
    dxccPrefixes,
    programReferences,
    scpCalls,
    workedBefore,
    devices,
    peerCursors,
    settings,
    shortcutBindings,
    qsosAccountTime,
    qsosCall,
    qsosContestSession,
    qsoSyncAccountState,
    syncJournalAccountAt,
    programReferencesPosition,
  ];
  late final Shape0 accounts = Shape0(
    source: i0.VersionedTable(
      entityName: 'accounts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 stationProfiles = Shape1(
    source: i0.VersionedTable(
      entityName: 'station_profiles',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(account_id, remote_id)'],
      columns: [
        _column_0,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 contestDefinitions = Shape2(
    source: i0.VersionedTable(
      entityName: 'contest_definitions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_12,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 contestSessions = Shape3(
    source: i0.VersionedTable(
      entityName: 'contest_sessions',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_0,
        _column_36,
        _column_10,
        _column_37,
        _column_38,
        _column_39,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 activations = Shape4(
    source: i0.VersionedTable(
      entityName: 'activations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_0,
        _column_10,
        _column_48,
        _column_49,
        _column_50,
        _column_37,
        _column_38,
        _column_39,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 qsos = Shape5(
    source: i0.VersionedTable(
      entityName: 'qsos',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_0,
        _column_10,
        _column_37,
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_64,
        _column_65,
        _column_66,
        _column_67,
        _column_68,
        _column_21,
        _column_18,
        _column_19,
        _column_20,
        _column_22,
        _column_23,
        _column_69,
        _column_70,
        _column_71,
        _column_72,
        _column_73,
        _column_74,
        _column_75,
        _column_50,
        _column_76,
        _column_77,
        _column_78,
        _column_79,
        _column_80,
        _column_81,
        _column_82,
        _column_83,
        _column_84,
        _column_85,
        _column_86,
        _column_87,
        _column_88,
        _column_89,
        _column_90,
        _column_91,
        _column_92,
        _column_93,
        _column_94,
        _column_95,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 qsoSync = Shape6(
    source: i0.VersionedTable(
      entityName: 'qso_sync',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(qso_id, account_id)'],
      columns: [
        _column_96,
        _column_10,
        _column_97,
        _column_98,
        _column_99,
        _column_100,
        _column_101,
        _column_102,
        _column_103,
        _column_104,
        _column_105,
        _column_106,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 syncJournal = Shape7(
    source: i0.VersionedTable(
      entityName: 'sync_journal',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [],
      columns: [
        _column_107,
        _column_10,
        _column_108,
        _column_109,
        _column_110,
        _column_111,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 contestLinks = Shape8(
    source: i0.VersionedTable(
      entityName: 'contest_links',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(session_id, qso_id)'],
      columns: [_column_112, _column_96, _column_113, _column_114],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 serialAllocations = Shape9(
    source: i0.VersionedTable(
      entityName: 'serial_allocations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(session_id, serial)'],
      columns: [_column_112, _column_115, _column_108, _column_116],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 programRules = Shape10(
    source: i0.VersionedTable(
      entityName: 'program_rules',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(program)'],
      columns: [_column_48, _column_28, _column_117],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 referencePacks = Shape11(
    source: i0.VersionedTable(
      entityName: 'reference_packs',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_118,
        _column_119,
        _column_120,
        _column_121,
        _column_25,
        _column_122,
        _column_123,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 dxccEntities = Shape12(
    source: i0.VersionedTable(
      entityName: 'dxcc_entities',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(dxcc)'],
      columns: [
        _column_124,
        _column_12,
        _column_125,
        _column_126,
        _column_127,
        _column_128,
        _column_129,
        _column_130,
        _column_131,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 dxccPrefixes = Shape13(
    source: i0.VersionedTable(
      entityName: 'dxcc_prefixes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(prefix_or_call, exact)'],
      columns: [
        _column_132,
        _column_133,
        _column_134,
        _column_135,
        _column_136,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape21 programReferences = Shape21(
    source: i0.VersionedTable(
      entityName: 'program_references',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(program, ref)'],
      columns: [
        _column_48,
        _column_137,
        _column_12,
        _column_138,
        _column_139,
        _column_140,
        _column_141,
        _column_142,
        _column_155,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape15 scpCalls = Shape15(
    source: i0.VersionedTable(
      entityName: 'scp_calls',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(call)'],
      columns: [_column_51],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape16 workedBefore = Shape16(
    source: i0.VersionedTable(
      entityName: 'worked_before',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(account_id, call, band, mode)'],
      columns: [
        _column_10,
        _column_51,
        _column_54,
        _column_56,
        _column_15,
        _column_14,
        _column_143,
        _column_144,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape17 devices = Shape17(
    source: i0.VersionedTable(
      entityName: 'devices',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [_column_0, _column_12, _column_145, _column_146, _column_147],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape18 peerCursors = Shape18(
    source: i0.VersionedTable(
      entityName: 'peer_cursors',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(device_id)'],
      columns: [_column_148, _column_149],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape19 settings = Shape19(
    source: i0.VersionedTable(
      entityName: 'settings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_150, _column_151],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape20 shortcutBindings = Shape20(
    source: i0.VersionedTable(
      entityName: 'shortcut_bindings',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(command_id, platform)'],
      columns: [_column_152, _column_153, _column_154],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index qsosAccountTime = i1.Index(
    'qsos_account_time',
    'CREATE INDEX qsos_account_time ON qsos (account_id, time_on)',
  );
  final i1.Index qsosCall = i1.Index(
    'qsos_call',
    'CREATE INDEX qsos_call ON qsos (call)',
  );
  final i1.Index qsosContestSession = i1.Index(
    'qsos_contest_session',
    'CREATE INDEX qsos_contest_session ON qsos (contest_session_id)',
  );
  final i1.Index qsoSyncAccountState = i1.Index(
    'qso_sync_account_state',
    'CREATE INDEX qso_sync_account_state ON qso_sync (account_id, state)',
  );
  final i1.Index syncJournalAccountAt = i1.Index(
    'sync_journal_account_at',
    'CREATE INDEX sync_journal_account_at ON sync_journal (account_id, at)',
  );
  final i1.Index programReferencesPosition = i1.Index(
    'program_references_position',
    'CREATE INDEX program_references_position ON program_references (program, lat, lon)',
  );
}

class Shape21 extends i0.VersionedTable {
  Shape21({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get program =>
      columnsByName['program']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ref =>
      columnsByName['ref']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get region =>
      columnsByName['region']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<double> get lat =>
      columnsByName['lat']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<double> get lon =>
      columnsByName['lon']! as i1.GeneratedColumn<double>;
  i1.GeneratedColumn<int> get validFrom =>
      columnsByName['valid_from']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get validTo =>
      columnsByName['valid_to']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get active =>
      columnsByName['active']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_155(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'active',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 1 CHECK (active IN (0, 1))',
      defaultValue: const i1.CustomExpression('1'),
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(from1To2: from1To2, from2To3: from2To3),
);
